name: Format, types and lint check
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Pipx
        uses: CfirTsabari/actions-pipx@v1

      - name: Install Poe The Poet
        run: pipx install poethepoet

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: 1.8.3

      - name: Installing dependencies...
        run: poetry install --no-interaction --with dev

      - name: Formatting check
        if: always()
        run: poe format-check

      - name: Linting
        if: always()
        run: poe lint-check

      - name: Type checking
        if: always()
        run: poe type-check
